### ISSUE TITLE
[Perception] Scenes 5 & 6

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#101]
I wonder if it would be worth switching the order of 5 and 6 so that captions and sign language come before vibrations. Or these could be combined (maybe not, because of the visuals used in the video). 
Maybe the order is not so important.

**Comment by eoncins** [comment]
+1 switching the order will also be consistent with scene 1 in which it is stated "People perceive information through different senses. This includes perceiving information through hearing, seeing, and feeling." 

So "feeling" should be after "hearing".

**Comment by nitedog** [comment]
There is a nice sequence here that shows the overlapping user needs, I think:

- people who are blind or who have low vision rely on hearing or touch rather than sight
- Alike people who are blind, people who are Deaf and Hard of Hearing often use haptic information
- People who are Deaf and Hard of Hearing also rely on seeing instead of hearing
- Some people with reading disabilities also convert content into formats they can better understand
