### ISSUE TITLE
[Navigation] Scene 1

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-people-use-web-videos#103]
Suggestion: Maybe replacing "abilities" with "needs"? Skills is a term close related to abilities.

"When content is designed right, people can browse it effectively according to their preferences, skills and needs.

**Comment by nitedog** [comment]
I think the reason why EOWG is using "abilities" rather than "needs" in the opening sentence of the reference page, is because sometimes "needs" can come across a little negative/patronizing (eg. "people with disabilities are needy"). I think the term "abilities" plays on "disabilities" to avoid the issue. Happy to discuss this, I'm not entirely sure which works better.
