### ISSUE TITLE
[Ilya] Overall - Missing personal touches

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#134]
This script doesn't feel as 'strong' (impactful/descriptive?) as the written script. For instance, in the written script Ilya works with spreadsheets which explains more why she needs a computer for work (and adds some complexity to the tasks). 

There's also a bit more about Ilya's day in the written script - you get a feel for what she does at work and her hobbies. The video script has more about technical terms (e.g., headings, lists, and CAPTCHAs) but loses how these fit into a day-in-the-life (e.g., online forums).

Thinking we should put more personal touches back in the script aligned with the written script.

**Comment by nitedog** [comment]
This script is already quite long but I tried to weave in a few personal touches as suggested:

- Scene 4: added "As a senior accountant" ahead of "I was really concerned about that move because of the many online spreadsheets, presentations, and documents that I need to use and edit", to give a glimpse on her job role.
- Scene 5: changed "conferencing tool that our clients uses" to "conferencing tool that I need to use to train our clients", also to emphasize her seniority and the type of work she needs to carry out.
- Scene 6: added "Outside work, I enjoy cooking, knitting, and travel. I join online groups to find recipes, knitting patterns, and to book travel" ahead of the part on CAPTCHA, to give a better idea of how this impacts her seemingly busy personal life.

**Comment by MicheleAWilliams-A11y** [comment]
Agree this is feeling more like we're learning about her day and activities -- I can hear and visual it more in my head as I read this version. Thanks!
