### ISSUE TITLE
[Ilya] Possible to add using mobile speech assistants?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#135]
I know this isn't in the written script but would be really impactful to explain that Ilya likes her mobile phone in large part because she can use voice interfaces like Siri to shortcut her activities.

**Comment by nitedog** [comment]
I tried adding something in scene 3 where it talks about mobile phones but it got quite confusing because it was jumping back and forth between voice interfaces and screen reader. It also feels like the term "voice interfaces" needs some description, which adds to the already long (and dense) script. I'm not sure we can fit this in here quite easily but will leave this issue open for further ideas.

**Comment by bakkenb** [comment]
I kind of like scene 3 the way it is written now.

For reference in case it changes in the future:

> Some screen readers are quite complex and take a lot of time to learn properly. Today there are more options, including screen readers built directly into mobile phones and computers. Actually, I’d use my phone for everything but I need to use my computer for work. This means learning and using two different screen readers, each with their own functions and quirks.

The only thing that is missing from Michele's initial comment is to add something about Siri. "Actually, I’d use my phone for everything because I can use Siri for most tasks, but I need to..."

Just an idea.

**Comment by nitedog** [comment]
We can't name a particular product. We would need to say something like "Actually, I’d use my phone for everything because I can use the digital assistant for many tasks, but I need to...". My worry is that "digital assistant" seems quite jargony (and "speech" or "voice assistant" seem less accurate), so we would need an additional sentence or two to explain that term then come back again to screen readers. Or do people feel that "digital/speech/voice assistant" is sufficient on it's own?

**Comment by jade-mc** [comment]
That's tricky... I don't think people will know what 'digital assistant' means, we're so far down the line of associating product names for tech in this particular area. I love the idea though, will kick this round my head for a bit this morning, see if I can come up with anything profound...!

**Comment by MicheleAWilliams-A11y** [comment]
If the team wants to include this (yay!) then can't we just describe the actions rather than give it a name? Seem this is what a non-technical person would do in conversation anyway. 

E.g., "If I could, I would use my phone for everything, especially since I can often just speak the actions I want and skip all the typing and swiping. [Cut to Ilya using a voice assistant for a generic command.]"

This may mean reordering how we describe the screen reader on mobile but should be easy if so _(not currently looking at the script as I type this comment, but wanted to jot it down before other activities interfered)_.

**Comment by nitedog** [comment]
Changed scene 3 to (see also #159):

> Some screen readers, like the one on my work computer, are quite complex and take a lot of time to learn all the keyboard commands. I prefer the screen reader on my mobile phone, which is much easier to use. I can also just speak most actions I want on my phone instead of all the typing and swiping. If I could, I would use my phone for everything but I can't access my company network with personal devices.
