### ISSUE TITLE
[Preety] Scene 4

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#141]
Suggestion: Or, the reading jumps around in confusing ways because the document/page hasn't been set up correctly.

**Comment by nitedog** [comment]
The entire part reads as follows:

> But not all books are accessible, which is really frustrating. Some cannot be read aloud. Or, the reading jumps around in confusing ways. Or, I can't change the fonts and spacing.

Each issue is related to books that are not accessible. I think repeating "because the book is inaccessible" with every issue is not a natural way of speaking. We will advise the narrator to read this accordingly, and also the visuals with support this. Would that be sufficient to address your concern?

**Comment by jade-mc** [comment]
My point here was more to do with the idea of it jumping around, it might not be clear to the audience why that happens so it might need explaining a little (but if you don't feel that's the case then that's fine with me.)

**Comment by nitedog** [comment]
Added explanation.
