### ISSUE TITLE
[All User Story Scripts] Need more personal introduction

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#168]
One thing I realized late in reading these is that none of the post-Martine scripts have an introduction beyond Name and Disability. We are missing the "how I spend my time" part such as "student" or "accountant". 

Since these are "user stories", I think it's important to not sound so 'clinical' in these introductions, even if we get to those things later in the script.

**Comment by nitedog** [comment]
Made the following changes:

- Alan: (scene 2) changed "A keyboard that I can use is really important to me." to "I've been working as a reporter for over 20 years, so a keyboard that I can use is really important to me."
- Ian: (moved from scene 2 to scene 1) "I work for a software company three bus stops from my home. "
- Ilya: (scene 1)  added "I'm a senior accountant at a large company." (and removed "As a senior accountant" from scene 4)
- Lee (scene 1) added "I love online shopping because it's often easier for me." and adjusted next scene (scene 2) to now say "I have difficulty distinguishing among red, green, orange, and brown, all of which appear to me as kind of murky brown. In a store, I often can't tell the color of two shoes or two shirts beside each other. I use an online shop that names the colors in addition to showing them."
- Luis: (moved from scene 2 to scene 1) "I love basketball! I played on my school team and I am now playing in a club."
- Martine: no change.
- Noor: (scene 1) added "I'm a high school senior at my School for the Deaf" and made further edits.
- Preety: no change.
- Yun: (scene 1) added "I'm a retired architect and professor." and made further edits.
