### ISSUE TITLE
[Martine] Automatic captions 0:35 - 1:15

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-people-use-web-videos#173]
We may be at real risk for obsolescence with this sentence: 

> "This is more accurate than automatic captions, which don’t recognize specialized terms and names. They also don’t recognize who is speaking and can run sentences together, which makes it hard to keep up. " 

Google Meet does ID the speakers and others are soon to follow.  Our own experience is that many people have come to prefer auto captions due to the immediacy of the display - there is less lag time.  Accuracy of human captions is quite variable as well.  If the captioner has not been prepped with specific terms they too can get them wrong. At AccessU we committed to auto captions for all web casts and made human captioning and ASL an option that could be requested 2 hours in advance. We had 12 deaf attendees and only one requested the human captioners and three the ASL. The surveys indicated that most of the deaf attendees felt that auto captions have significantly improved. Since it was a lecture, the speaker ID was not an issue for most of teh deaf attendees. It's complex and will be hard to cover all of the factors in this short video. 

I only suggest that we be a bit more tentative - maybe "This is USUALLY more accurate...since human captioners can be prepared with a glossary of special terms. and more consistently identify  a change in speaker.

**Comment by bakkenb** [comment]
Good points. Microsoft Teams also now provides the name of the speaker in real-time.

**Comment by LidiaBest** [comment]
Hello. Issue with auto captions is the contentious one and we need to be careful here. While the auto captioning improves, it still have issues of accuracy levels which reduces it's usability. 
We also need to be aware of who is actually relying on human captioning and who may be OK with auto captioning. 
Deafened and Deaf people will demand accuracy and rely on humans, who are simply "their ears". Hard of hearing people, both using hearing aids and CI will also fall back on their hearing as a back up and they are more likely manage lack of accuracy in captioning, because they have some auditory input.

**Comment by JEGrisham** [comment]
As a deaf person, for me, in general, auto captions are not reliable and the human captioning is more reliable. Human captioners do have a higher level of accuracy and timing. Maybe change “accurate” to “reliable.” 

Since this is Martine talking ... this can be her "opinion" about the reliability as everyone can have an opinion about this.  The issue with autocaptions is not necessarily specialized terms and names…it’s not even the fact speakers are not always identified, but rather variations in speaker’s speech, accents, background noises, etc. Auto caption programs with filters that filter out names that are legitimate are an issue. Plus using auto captions can have legal implications.

**Comment by LidiaBest** [comment]
Agree with the comment

> As a deaf person, for me, in general, auto captions are not reliable and the human captioning is more reliable. Human captioners do have a higher level of accuracy and timing. Maybe change “accurate” to “reliable.”
> 
> Since this is Martine talking ... this can be her "opinion" about the reliability as everyone can have an opinion about this. The issue with autocaptions is not necessarily specialized terms and names…it’s not even the fact speakers are not always identified, but rather variations in speaker’s speech, accents, background noises, etc. Auto caption programs with filters that filter out names that are legitimate are an issue. Plus using auto captions can have legal implications.

**Comment by jade-mc** [comment]
Was just about to come in with the legal angle and the issue of reliance, until auto captions are 100% accurate, then they're an issue. I like the idea of adding 'usually' or another adverb in there though to tidy this up a bit.
