### ISSUE TITLE
[Preety] Global concern about 13-year-old persona 

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#176]
[HIGH PRIORITY — Consolidated COGA feedback]
Preety is currently a 13-year-old with dyslexia and ADHD. COGA strongly recommends that EO either make Preety a college student (18 or older) or consult W3C's Accessibility for Children community group to ensure this script (and user story) adequately addresses the needs of children with disabilities. 

For example, the current script does not mention online safety, which is a major concern for kids in general and an even greater concern for kids with dyslexia and ADHD, who likely struggle with:
- Impulse control
- Low self-esteem
- Difficulty assessing what is or isn’t a “safe” website, and
- Other issues that the Accessibility for Children community group is better situated than COGA to address with EO.

**Comment by bakkenb** [comment]
This is a very interesting, valid point. Thank you Julie (COGA group) for explaining it so clearly. The only concern or question I have on this is wondering if it is getting a little out of scope. Does online safety fall under the accessible digital content umbrella. I can see and understand some of the overlap, but wondering if this would distract a little too much from people learning about the needs of dyslexia and ADHD to be able to have equal access to digital content. Thanks for the great input. Interested in other's opionons.

**Comment by iadawn** [comment]
Preety's age was included to differentiate her a bit from Noor. Her age could be removed without any change being required to the persona itself. This would leave the reader to age her based on their interpretation of 'student'.

I agree with @bakkenb in that adding in online safety would divert from the key purpose of this resource. Online safety is a significant topic in itself and there wouldn't really be the opportunity to sufficiently address it.

**Comment by lseeman** [comment]
Also sometime people think that you grow out of dyslexia and it only matters for children.

**Comment by julierawe** [comment]
Why is Preety's online safety "outside of the scope" of this series on "How People with Disabilities Use the Web"?

Every day untold numbers of people use the web and get scammed — this is why COGA is suggesting adding fear of scams to the script about Yun, the retired professor with short-term memory loss. 

Every day untold numbers of children use the web and encounter other kinds of predators. This is an accessibility issue in the broadest sense. Who has access to kids in online spaces? What can parents and tech developers do to keep kids safe? 

Online safety doesn't have to be a huge part of Preety's script. Maybe all that is needed is to add a sentence about Preety being grateful that her mum set up parental controls to keep creepy people from messing with her.

Not sure what the solution is, but it remains very concerning to have a 13-year-old persona without specifically acknowledging the accessibility needs of children with disabilities.

**Comment by jade-mc** [comment]
My main hesitation here is that I agree that it falls outside the scope of the purpose of these videos. 
Plus, would it be authentic for Preety to be grateful for having the parental controls set up? Perhaps if this wasn't first person, it might be something a third person voice over could achieve more naturally.

**Comment by shawnthompson** [comment]
I see two concerns here:

1. Giving an age to Preety (darn autocorrect keeps changing her name to Pretty)
2. Online safe for people with disabilities. 

For the first one (1.) I believe one of COGA's concern with Preety being young is as per @lseeman's comment above:

> Also sometime people think that you grow out of dyslexia and it only matters for children.

Making her an adult student could help steer people away from that thought of children outgrowing these types of disabilities.

For the second one (2.), I believe it's a very important issue people with disabilities face everyday on the web but it might out of scoop for these videos.

**Comment by rainbreaw** [comment]
I'm concerned that the comment thread is diverging from the principal concern being expressed.

The concern is this: **if Preety is a child**, then there are a couple of huge risks that the video will be taking. These risks include:

- Furthering the stereotype or misconception that dyslexia and ADHD only impact children (as Lisa mentioned),
- Being negligent of additional concerns and laws surrounding tech use by children,
- Being perceived as "irrelevant" because some of those additional concerns become restrictions, and creators/producers may think that this doesn't apply to them since the limitations or requirements they have to follow aren't represented.

Taken together, all of these concerns could diminish the benefit that this video will have. 

In order to address this, there are two options:

1. Make Preety an adult (she could even be a 1st year college student, which would enable the writers to keep the script pretty much identical since it is reasonable that a college student might live with their parents).
2. Address the issues above directly in the script (which many of the comments are focusing on, and calling out of scope).

Option 1 is much easier because the scope conversation becomes irrelevant and nearly nothing has to change in the script. This is what I would recommend. 

I'll add, as someone who used to produce films and work with talent, that it is a lot easier and less expensive to work with 18 year old actors than with 13 year old actors, so making this change will reduce production costs and logistics, as well.

**Comment by alyssapanetta** [comment]
I think identifying Preety simply as "a first-year college student" is the best path forward. 

It makes her age less relevant (anyone could start college at any point in their lives) while still telling the story of a disabled user in a new environment facing new challenges with online research. As the web designer for an academic library, I've seen first hand what a "new world" that is for all users and how overwhelming it can be for anyone with cognitive disabilities.

**Comment by shawna-slh** [comment]
I very much like the inclusion of a younger persona. I think it's good to help readers understand accessibility isn't just as issue for adults. It'd be really nice if we could address the related issues, and comfortably leave the persona a younger person. (My guess is that the Accessibility for Children CG folks would appreciate having a younger persona.)

One thing to keep in mind is that the videos are just one small piece of this resource, and we can't and don't need to address every issue in the videos. For example, the issue that people don't outgrow ADHD and ADHD impacts adults, too, maybe could be mentioned in https://deploy-preview-113--wai-people-use-web.netlify.app/people-use-web/abilities-barriers-cognitive/

**Comment by nwhysel** [comment]
An aside to this discussion, I live in NYC so hear random thoughts and conversations all the time. I was walking along 14th street and heard a very angry person behind me yelling into her phone “Don’t be giving me that ADHD s**t. He’s a grown up!” Clearly this person and many like her assume these conditions affect children and we grow out of it. Most of my friends with the condition were diagnosed as adults after noticing problems with their own children. As an adult their physicians never asked if they thought it was a problem. Now, with COVID causing cognitive issues, physicians are being asked to discuss anxiety and related disorders with their <65 adult patients. So I do think it’s an interesting idea to have Preety be a young college student rather than a child. But I also think that the severity of effects on a developing brain is of interest, too. If a child is unable to overcome the effects of ADHD while so much school learning is happening in online spaces, it exacerbates it for the adult with ADHD that they will become.

**Comment by shawna-slh** [comment]
Another possibility is re-defining another persona to be younger.

**Comment by nitedog** [comment]
Ref: feedback from the [Accessibility for Children Community Group](https://docs.google.com/document/d/1WvxEaI0KVVTENu3dO4BhLTV-fFWayPK7tLz8pKIyvH8/edit#heading=h.bnbhrji4je4d).

1. Video does not mention specific age of the person
2. Addressed comments from COGA TF on stereotypes/cliches
3. Added aspect of parent controls and online safety concerns
4. Added aspect of not growing out of the disability/condition

See also changes for issues: #183 #184 #185 #187 #188 #192
