### ISSUE TITLE
[Noor] why interpreter for speaking?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-people-use-web-videos#213]
From @sharronrush 

> I was not clear why Noor needs the interpreter to speak for her. Many deaf/blind people do speak. Can this be explained?

**Comment by bakkenb** [comment]
I am assuming that there is a wide spectrum for deaf/blind of abilities (as we all know about any disability population). I agree many deaf/blind do speak and many don't for various reasons. In the source content "Noor, teenager who is deaf and blind." it says that she communicates using sign language. I think that is why the video script went with this degree of ability, so that it would match more closely to the existing page. 

Many of these User Story videos and source pages just pick one example of one individual in that population that is on a wide spectrum of abilities. Sometime hard to know what is the best representation for that one user story example.

**Comment by sharronrush** [comment]
Then her introduction should be "Noor, teenager who is deaf, blind, and nonverbal." Otherwise it gives the impression that deaf/blind people don't speak which is entirely untrue.

**Comment by LidiaBest** [comment]
There is a very wide spectrum of deafblind users, in a nutshell, Deaf( using sign language and have reduced vision) or oral( speaking ( relying on auditory input such as CI, hearing aids, and enlarged text).
There are also some people who can no longer see but still hear with CI or hearing aids.
It is worth considering two separate videos of different representation of deafblind community.

**Comment by JEGrisham** [comment]
I get the concerns addressed about DeafBlind also speaking. I think the script as is right now (no reference to interpreter speaking for me) is appropriate because Noor happens to use sign language and there’s no reference to speaking ability. Regarding the comment about nonverbal – that is not a term that I’ve heard used related to deaf or hard of hearing individuals who do not speak and would not use that. The references to non-speaking deaf/HOH are generally "doesn’t speak," "uses sign language," or even "uses sign and not spoken language." In reality, many non-speaking deaf/HOH individuals are verbal -- but they do not use spoken language for communication. 

I agree about videos representing different communication options, but if that's not the preference, then I would suggest keeping Noor very "neutral" as it appears now.

**Comment by JEGrisham** [comment]
One more thing on Noor -- Seq 1 says: Hi! I’m Noor, a high school senior at my School for the Deaf. I’m deafblind.

I do recommend changing all instances of deafblind or even deaf-blind to DeafBlind. I have a friend who is involved in the DeafBlind community and he says that the majority of them use DB (capitals).

**Comment by nitedog** [comment]
Tweaked second sentence to say "As a Deaf child, I learned sign language early on", to further clarify Noor's use of sign language.
