### ISSUE TITLE
[Martine] Seq. 4 - Wording change for lip reading

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#51]
To me this sentence does not seem quite right:

> I learned lip reading over the years because of such situations but it’s not accurate.

It isn't that lip reading is not "accurate" to this person. It is that it is not reliable - maybe because that are not that good at it, or because people move to much or cover their mouths.

What about:

> I learned lip reading over the years because of such situations but it’s not **_always reliable for me_**.

**Comment by nitedog** [comment]
Changed to:

> I learned lip reading over the years because of such situations but it's not always reliable.

Rationale: I think the "for me" part could be misunderstood as under-performance of the lip-reader. That is, if they train more they could do this all day. As far as I know, it is seldom that people find lip reading as reliable as sign language, even if they are really good at it (also because of external factors, such as covered mouth etc.).
