### ISSUE TITLE
[Martine] is this how Martine would speak?

### ISSUE THREAD

**Issue by beltonTPG** [w3c/wai-people-use-web-videos#71]
Typo in the visual instructions of 1:40 - 2:05 - "We see Martine having difficulty understanding a page with with long and justified paragraphs," (duplicate "with").

Overall question about Martine's dialog: At times it seems a bit formal, and perhaps overly wordy. Have we thought about whether this is how Martine's explanation of her experience would be translated from sign language to spoken English? Was a sign language interpreter consulted?

Content-wise I think it is good.

**Comment by nitedog** [comment]
Can you say which parts specifically you think are overly formal and/or wordy?

**Comment by beltonTPG** [comment]
First of all, I have exactly zero expertise in sign language and sign language interpretation, so please take this note with that in mind. 
My (limited) understanding is that sign language is a distinct and unique language, and yet the way the script reads, it seems fairly formal (overly scripted rather than someone just relaying their experience) and in the places where some informal language is attempted, it makes me wonder if it is an accurate representation of the sign language that would be used to convey this language, or if we are using strictly English idioms ("And because none of us are getting any younger, **you know**, I often find myself needing to adjust the text size and colors of the captions..."). 
I am just wondering if it would be a good idea to have a sign language interpreter review/edit the script to ensure the language and language patterns that are used reflect how they would generally interpret the ideas being conveyed.
I hope this make sense.

**Comment by LidiaBest** [comment]
Hello. Thanks for inviting me to comment.  For the 1.15 - 1.40 , since we describe a signa language user, we need to be careful when we present lipreading. First of all, the script should not request speakers to speak slowly, instead it should be to speak normally, not to slow and not to fast. Ensuring their mouths are not covered or obstructed in any way.

Second issue is the accuracy of lipreading ( reliable). There are too many factors related to accuracy of lipreading, one of the is literacy. Native sign language user will not always have same level of literacy as hard of hearing or deafened person and understanding with lipreading vary between 30% to 70%.  I would say, instead of making statement that lipreading is not always reliable, it would be safer for Martine to say " I do not find it working and reliable for me".

**Comment by JEGrisham** [comment]
> Overall question about Martine's dialog: At times it seems a bit formal, and perhaps overly wordy. Have we thought about whether this is how Martine's explanation of her experience would be translated from sign language to spoken English? Was a sign language interpreter consulted?

**Comment by JEGrisham** [comment]
I also want to address the lipreading piece as a lifelong lipreader, or rather speechreader. 

I agree with the comment about speaking slowly and clearly. Speaking slowly can be cumbersome for speechreaders. The more appropriate way would be to say “speak normally and clearly.” Now since this is something “Martine” is saying – I personally would say “have them speak a little slower and clearly, if needed.” The latter is probably the better option here. Additionally, I agree with the comment about lipreading not always reliable. Since “Martine” is speaking, the phrase (but it’s not always reliable) in Seq 4 could be changed to: "… but lipreading does not always work for me." This would be a more realistic statement.

**Comment by nitedog** [comment]
- Changed to "For my classes, I schedule interpreters who interpret the lectures and conversations, and voice for me" (did not add "disability office" because it is US-specific)
- Changed to "I learned lip reading over the years because of such situations but it's not always reliable for me"
- Removed (unintentional) reference to closed captions (just captions)
- Removed part about speaking slowly (just speaking clearly)
- Other minor edits to align tone with the comments on how Martine would speak
