### ISSUE TITLE
[Auditory] editorial suggesttions

### ISSUE THREAD

**Issue by beltonTPG** [w3c/wai-people-use-web-videos#72]
Typo in visual instructions for :10 - :25: "We realize that the persopn (#1) "

Narration in 1:10-1:30 - "Volume controls to turn up the audio playing independently of other system sounds makes it easier for people to hear too." makes is sound like it works for hard of hearing people and regular people too. I think "for people" can be omitted, as the previous sentence already stated "for many people with auditory disabilities, with and without hearing aids."

Narration in 1:30-2:00 - "While many people with auditory disabilities do not know sign language, for many people sign language is the primary language for communication." this is very clunky - "while many people... for many people... I would suggest "While many people with auditory disabilities do not know sign language, for some it is the primary language for communication."

**Comment by nitedog** [comment]
1. Fixed typo as suggested.
2. Removed "for people" as suggested.
3. Reworded as suggested with minor tweak: "While many people with auditory disabilities do not know sign language, for many others it is the primary language for communication" (now says "for many others" rather than "for some" as suggested).

**Comment by nitedog** [comment]
Closing this issue, please re-open if you feel your comments have not be addressed adequately.
