### ISSUE TITLE
[Martine] using chat to communicate with her colleauges?

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-people-use-web-videos#74]
Scene 4 highlights the challenges Martine faces when there are no interpreters and she has to really on lip reading. Wouldn't it be interesting to also illustrate how Martine communicates with the other participants in the meeting? I guess she would probably really on a chat mechanism, with all the limitations that impose for real-time discussions.

**Comment by nitedog** [comment]
Added new scene:

**Audio:** I also use chat functions in many tools. Some chat tools support realtime text rather than line-by-line text messages only. This is much more interactive, and I can engage with my friends in text conversations as others do by voice.

**Video:** [New scene.] We see Martine using a messenger tool and chatting with other people in realtime text. [We see a split screen and both people are typing to each other at the same time]. Martine is engaged in the discussion and smiling as she types.

**Comment by carlosapaduarte** [comment]
I like the new scene. 

I'll leave an idea for your consideration: swap scenes 4 and 5, that is, start with the lip reading scene and then move to the chat scene. Somehow I think I prefer the script to move from the recorded video watching scene, to the lip reading that can be used for recorded video watching as well as for live video but that creates awareness to the existence of a one-way communication channel, to the chat scene where two-way communication is supported.
But I won't be against keeping the order of the scenes as is.

**Comment by MicheleAWilliams-A11y** [comment]
I'm wondering why we added a new scene for chat? The original comment was about using a chat function in a video conference meeting (which I think would still happen so as not to rely solely on lip reading). Is this so we can get in the "real-time" chat function?

**Comment by nitedog** [comment]
I had added a new scene to sneak in real-time text. I switched the two scenes as proposed by @carlosapaduarte as a continuation of the initial lip reading scene as proposed by @MicheleAWilliams-A11y -- does this now address the issue for both of you?

**Comment by carlosapaduarte** [comment]
That works for me. I enjoy the solution.

**Comment by bakkenb** [comment]
This works for me as well.
