### ISSUE TITLE
[Auditory] cochlear implants controversial

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#80]
Cochlear implants are controversial. I'm thinking that we probably don't want to include them to avoid controversy. (If there is a very strong reason to include them, probably best to be in the middle of the video, not the beginning or ending.)

**Comment by nitedog** [comment]
Initial reaction from the videos subgroup is that we do not feel comfortable completely removing all mention/display of people with cochlear implants. Issue #77 should help further tone this down to avoid any implied positions. This needs further review by EOWG and the broader community.

**Comment by nitedog** [comment]
During the [meeting of 29 July 2022](https://www.w3.org/2022/07/29-eo-minutes#item01) EOWG decided to:

1. Keep the current approach for now
2. Reach out for broader review by members of the Deaf and Hard of Hearing community
3. Keep this issue open and revisit this after we have had broader review

**Comment by LidiaBest** [comment]
I am surprised by lack of mention of hard of hearing people, instead we seem to be in a overall auditory disabilities, this is new to me. 
My suggestions are as follows:
- Auditory disabilities - a script based on person hearing, sometimes hard of hearing who has APD ( auditory processing disorder). It is about how brain process the audio input and can be difficult to understand for others. This is actually not representative of hard of hearing people and they will not see themselves represented here.

- CI are not controversial, except in Deaf Community, once upon a time, hearing aids were controversial in Deaf Community. 
- However it is correct that people have various success outcomes from great to not so great.

- There is a need to develop a separate script, which presents a person who is hard of hearing or deafened, using either hearing aids or a CI should be developed. Not sure if this particular group has been already represented but it is the largest group of those who have issues with hearing. They rely on lipreading, captioning and sound when using the web and online platforms. 
- 1.30- 2.00 " While many people with auditory disabilities do not know sign language, for many others it is the primary language for communication. - Vast majority of hard of hearing people do not know sign language but some may know it, it is however not their primary language, just a support for communication.
- 
1.30 -2.00 -"Sign language has a different grammar and vocabulary than spoken and written language, so some people might not be as fluent in reading and writing depending on the schooling they received" - not exactly correct if you take into account sign supported language, which some members of this group often used in schools and continue using daily. Those follow spoken language grammar and vocabulary.
- 
I hope the above comments demonstrate the need for separate scripts and much wider representation of those who are deaf or hard of hearing.

**Comment by JEGrisham** [comment]
I read through the script and as a deaf person myself (not capital D), I would leave the script as is. The general coverage of CI and hearing aids is very neutral as stated. There are many people in the Deaf community who wear cochlear implants and the controversy is primarily around early detection and implantation. 

I do agree that there’s a need to touch on hard of hearing. That community tends to fall thru the cracks; however, do note that there are those who are hard of hearing that use sign or they speak or both just like those who are Deaf or deaf.

**Comment by LidiaBest** [comment]
I would like to make the point related to hard of hearing people and sign language. 

What we ( hard of hearing people) see is an assumption in the society , putting hard of hearing people with deaf people in the same basket of functionality  and as a common denominator, sign language is presented as our communication tool. This could not be further from the truth and the community does fall through cracks, precisely because of such assumptions. Far too often, in many countries globally, hard of hearing people are given only one access : sign language and when they ask for captioning, hearing loops they are simply told that only communication access for them is sign language.
It is correct that some hard of hearing people sign, mostly because they were schooled in deaf schools or growing up in a family of sign language users, or simply joined deaf community and wished to learn sign language to talk to their deaf friends. This is a minority, which is not representative of hard of hearing people as the community relying on hearing technologies, assistive listening devices, lipreading and captioning. 

As a hard of hearing person, and their representative, I feel that we need to be mindful of the correct representation and we have responsibility towards that group as we develop videos, scripts which will be followed by many people who do not understand those important differences.

**Comment by JEGrisham** [comment]
Agree with you. I grew up oral deaf...no sign language so I grew up identifying as hard of hearing because of the misconceptions people had similar to what you mentioned above.  The gist of my comment should have been clearer which was simply that the hard of hearing gets neglected often when general things are published -- it's always about Deaf vs. deaf, but not HOH. I do agree that we need to be mindful about the representation. Perhaps there should be a user profile for a HOH person (who could also represent my group of oral deaf nonsigners).  :-)

**Comment by shawna-slh** [comment]
@iadawn Would be good to consider [Yun, retiree](https://deploy-preview-113--wai-people-use-web.netlify.app/people-use-web/user-stories-nine/) hard of hearing. That's packing a lot into one persona... though, realistic.

**Comment by shawna-slh** [comment]
I really appreciate the input on this issue. Seems like acceptable to include cochlear implant. 

I would like for us to be thoughtful in how they are presented and positioned.

**Comment by nitedog** [comment]
Adjusted script to:

1. better reflect people with reduced hearing and other specific types of people with auditory disabilities
2. move the cochlear implant scene a further down, to avoid potential distraction from the actual topic
